### PR TITLE
Added option for different sections

### PR DESCRIPTION
**Pull request by amitiwary999**
Updated code and added option for different section like calcutta, bengal, national, foreign, business and sports.

Signed-off-by: Amit Tiwary tiwarya9@gmail.com

### CODE REVIEW

**Comment by 0xTheProDev** [comment]
Why have you created separate web request for each topic. I would suggest to create a single GET request that gets resolved in real time according to user demand!

**Comment by amitiwary999** [comment]
@RudraNilBasu told me that he will do that part that's why I left it.

**Comment by RudraNilBasu** [comment]
I will do it by Monday/Tuesday (hopefully)

**Comment by 0xTheProDev** [comment]
Why everything has to be done by @RudraNilBasu ? @mouri11 is interested to work on the project independently, I would rather suggest him to guide through the project and let him do it.

**Comment by amitiwary999** [comment]
@Progyan1997 Because I asked @RudraNilBasu and he told me that he want to work on this. its a open source project any one can contribute to this project.

**Comment by RudraNilBasu** [comment]
I have started working on this a bit. I will also discuss with @mouri11 about it, will guide him through
it.

**Comment by amitiwary999** [comment]
@RudraNilBasu if you are busy then push whatever you have done. I will work on it.

**Comment by RudraNilBasu** [comment]
I have made the changes here: https://github.com/BytesClub/News/commit/c007a4d901da309dc10011eab6cbae81aab26f57

**Pull request closed without merging**
